### ISSUE TITLE
Update the zenhub/github domo connector with the pipeline names

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/domo#128] opened 2019-08-27 18:15 UTC
# Description
As a project manager I would like to track the work UX team is doing using a burn up/down chart. At the moment the data set does not have the pipelines' names in it. It would be greatly helpful if the connector can be updated with the pipeline names

# Acceptance Criteria
Give criteria for acceptance.

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else

**Comment by BruceP99166** [comment] 2019-10-17 21:11
duplicate of 136

**Closed by BruceP99166** 2019-10-17 21:11 UTC
